"""Game constants and configuration."""

# Display
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60
TITLE = "Hacker Crush"

# Grid
GRID_ROWS = 8
GRID_COLS = 8
CELL_SIZE = 64
GRID_OFFSET_X = (WINDOW_WIDTH - GRID_COLS * CELL_SIZE) // 2
GRID_OFFSET_Y = 80

# Colors (Hacker Green Theme)
COLOR_BG = (13, 13, 13)  # #0D0D0D
COLOR_GRID = (26, 26, 26)  # #1A1A1A
COLOR_PRIMARY = (0, 255, 0)  # #00FF00
COLOR_SECONDARY = (0, 204, 0)  # #00CC00
COLOR_ACCENT = (51, 255, 51)  # #33FF33
COLOR_DANGER = (255, 0, 0)  # #FF0000
COLOR_WHITE = (255, 255, 255)

# Candy Types
CANDY_TYPES = ["blackhat", "defcon", "ronin", "lock", "key", "virus"]
NUM_CANDY_TYPES = len(CANDY_TYPES)

# Special Candy Types
SPECIAL_NONE = 0
SPECIAL_STRIPED_H = 1
SPECIAL_STRIPED_V = 2
SPECIAL_WRAPPED = 3
SPECIAL_COLOR_BOMB = 4

# Scoring
SCORE_BASE = 10
SCORE_STRIPED_BONUS = 50
SCORE_WRAPPED_BONUS = 100
SCORE_COLOR_BOMB_BONUS = 500
CASCADE_MULTIPLIER = 1.5

# Animation Durations (milliseconds)
ANIM_SWAP = 120
ANIM_INVALID_SWAP = 150
ANIM_MATCH_CLEAR = 150
ANIM_CANDY_FALL = 80  # Per row - faster falling
ANIM_SPECIAL_CREATE = 250
ANIM_STRIPED = 180
ANIM_WRAPPED = 250
ANIM_COLOR_BOMB = 350

# Game Modes
MODE_ENDLESS = "endless"
MODE_MOVES = "moves"
MODE_TIMED = "timed"

# Moves Mode Config
MOVES_INITIAL = 30
MOVES_TARGET_BASE = 5000
MOVES_TARGET_MULTIPLIER = 2
MOVES_BONUS_PER_UNUSED = 100

# Timed Mode Config
TIMED_INITIAL_SECONDS = 90
TIMED_BONUS_SPECIAL = 3
TIMED_BONUS_COMBO = 5

# Endless Mode Config
ENDLESS_MAX_RESHUFFLES = 3
